# Generated by Django 4.0 on 2022-01-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tag',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='recipes.Tags', verbose_name='Тег'),
        ),
        migrations.AddField(
            model_name='tags',
            name='checkbox_style',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
