# Generated by Django 4.0 on 2022-01-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_tags_shoplist_favorite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoplist',
            options={'verbose_name': 'Список покупок', 'verbose_name_plural': 'Списки покупок'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='tags',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Слаг для шаблонов'),
        ),
    ]
