# Generated by Django 4.0 on 2022-01-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_shoplist_options_alter_tags_options_tags_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг для шаблонов'),
        ),
    ]
